config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  get '/dashboard', to: 'dashboard#show'

  resources :wallets, only: [:new, :create]

  resource :dashboard do
    collection do
      get '/wallets/:slug', to: 'wallets#show', as: "whallet"
    end
  end

  get '/transactions/new', to: 'transactions#new'

  get "/friends", to: "address_books#show", as: :friends

  namespace :api, default: { format: :json } do
    namespace :v1 do
      resource :transactions, only: [:create]
      resource :wallets, only: [:create]
      resource :address_books, only: [:update]
      resource :phones, only: [:update]
    end
  end

end

app/models/wallet.rb
require 'pkey_service'
require 'keycleaner_service'
require 'digest'

class Wallet < ActiveRecord::Base
  belongs_to  :user
  before_save :generate_keys, :assign_slug

  enum status: %w(basic primary)

  def generate_keys
    key_service = PKeyService.new
    self.private_key ||= key_service.private_key
    # refactor to delete the newlines in PKeyService
    self.private_key = self.private_key.delete("\n")
    self.public_key ||= key_service.public_key(self.private_key).delete("\n")
  end

  def address
    self.public_key
  end

  def balance
    Rails.cache.fetch("#{cache_key}") do
      clarke_service.parsed_balance(address)
    end
  end

  def to_param
    slug
  end

  def assign_slug
    self.slug ||= name.parameterize if name
  end

  def balance_with_id
    "#{name} - CLC: #{balance}"
  end

  def self.all_sent_transactions(wallets)
    wallets.map do |wallet|
      wallet.sent_transactions
    end.flatten.sort_by(&:created_at).reverse
  end

  def self.all_received_transactions(wallets)
    wallets.map do |wallet|
      wallet.received_transactions
    end.flatten.sort_by(&:created_at).reverse
  end

  def sent_transactions
    Transaction.where(from: self.public_key)
  end

  def received_transactions
    Transaction.where(to: self.public_key)
  end

private

  def clarke_service
    ClarkeService.new
  end

  def cache_key
    Digest::SHA256.hexdigest(
      sent_transactions.completed.pluck(:status).join +
      received_transactions.completed.pluck(:status).join +
      user.email + self.created_at.to_s
    )
  end

end

app/controllers/api/v1/wallets_controller.rb
class Api::V1::WalletsController < ApiController
  def create
    if params.dig("private_key") && !params.dig("private_key").empty?
      private_der = KeyCleanerService.clean_user_input(params.dig("private_key"))
      der_with_headers = KeyCleanerService.private_strict_format(private_der)
      keypair = OpenSSL::PKey::RSA.new(der_with_headers)
      @private_key = PKeyService.new(keypair).private_key
    end

    @wallet = Wallet.new(
      user_id:     current_user.id,
      private_key: @private_key,
      name:        params.dig("wallet_name")
    )

    if @wallet.save
      @wallet.primary! if current_user.primary_wallet.nil?
      render json: { message: 'success' }, status: 200
    else
      render json: { message: 'error' }, status: 500
    end
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :wallets
  before_action :require_login

  def show
    @wallet                = current_user.wallets.find_by(slug: params['slug'])
    @sent_transactions     = @wallet.sent_transactions
    @received_transactions = @wallet.received_transactions
  end

  def new
    redirect_to dashboard_path and return if current_user.wallets.exists?
    @wallet = Wallet.new
  end

  def create
    if params.dig("private_key")
      private_der = KeyCleanerService.clean_user_input(params.dig("private_key"))
      der_with_headers = KeyCleanerService.private_strict_format(private_der)
      keypair = OpenSSL::PKey::RSA.new(der_with_headers)
      @private_key = PKeyService.new(keypair).private_key
    end

    @wallet = Wallet.new(
      user_id:     current_user.id,
      private_key: @private_key,
      name:        "Default",
      slug:        "default"
    )

    if @wallet.save
      @wallet.primary! if current_user.primary_wallet.nil?
      flash[:notice] = "Wallet Created!"
      redirect_to dashboard_path
    else
      # need some validation
      flash.now[:notice] = "Error with Submitted Private Key!"
    end
  end
end

app/views/wallets/new.html.erb
<div class="landing-image-new-wallet">
  <%= render partial: 'layouts/nav' %>
  <div class="opacity-new-wallet">
    <%= render partial: 'layouts/flash' %>
    <div class="container">
      <div class="col-sm-4 col-sm-offset-2 col-md-6 col-md-offset-3 new-wallet">
        <div class="card new-wallet-message">
          <div class="card-header">
            You Need a Wallet.
          </div>
          <div class="card-block">
            <button type="button" class="btn btn-secondary btn-md card-title" data-toggle="modal" data-target="#walletinfo">
              What's a Wallet?
            </button>

            <p class="card-text xs-center"></p>
            <%= button_to "Generate a New Wallet", wallets_path, id: "generateWallet", class: "btn btn-lg btn-success" %>
            <div>
              <br/>
              <h4>or</h4>
              <br/>
            </div>
            <h5>Load an Existing Wallet by importing it's Private Key</h5><br>

            <%= form_for @wallet, url: "/wallets", :html => {:class => "form-horizontal center"} do |f| %>
              Private Key: <input type="text" name="private_key">
              <input id="createNewWallet" type="submit" value="Import Private Key" class="btn btn-primary">
            <% end %>
            <%= link_to "skip", dashboard_path, class: "skip" %>

          </div>
        </div>
      </div>
    </div>


<!-- Modal -->
<div class="modal fade" id="walletinfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">What is a Wallet?</h4>
      </div>
      <div class="modal-body">
        A ClarkCoin wallet is how you will be transferring your favorite
        cryptocurrency to other users. This wallet will store your private
        key(generated by us), your public address, and your balance. You will need this to get started. If you have your own private key and would like to use, that import it below.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">Ready!</button>
      </div>
    </div>
  </div>
</div>

app/views/wallets/show.html.erb
<%= render partial: 'layouts/nav' %>
<%= render partial: 'layouts/side_menu' %>
<div class="row flash-zone">
  <%= render partial: 'layouts/flash' %>
</div>
<div class="col-sm-12 col-xs-12 main-content-area user-keys">
  <br>
  <div class="row">
    <div class="page-header">
      <h4 class="animated fadeInUp"><%= @wallet.name %></h4>
    <br>
    <hr>
    </div>
  </div>
  <div class="row primary-wallet">
    <span class="primary-wallet-info">
      Balance: <%= @wallet.balance %> CLC
      <a class="pull-right" href="#" data-toggle="modal" data-target="#address"><span class="fa fa-tag" aria-hidden="true"></span>Your Address</a>
    </span>
    <br>
  </div>
      <!--  modal / -->
    <div class="modal fade" id="address" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Your ClarkeCoin Address</h4>
          </div>
          <div class="modal-body">
            <div class="inputs">
            Address: <input id="addy" type="url" value="<%=@wallet.address%>">
            <button id="copy_btn" class="addy"><i class="fa fa-clipboard"></i></button>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </span>
  <hr>
  <%= render partial: "/layouts/transactions" %>
</div>