config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  get '/dashboard', to: 'dashboard#show'

  resources :wallets, only: [:new, :create]

  resource :dashboard do
    collection do
      get '/wallets/:slug', to: 'wallets#show', as: "whallet"
    end
  end

  get '/transactions/new', to: 'transactions#new'

  get "/friends", to: "address_books#show", as: :friends

  namespace :api, default: { format: :json } do
    namespace :v1 do
      resource :transactions, only: [:create]
      resource :wallets, only: [:create]
      resource :address_books, only: [:update]
      resource :phones, only: [:update]
    end
  end

end

app/controllers/api/v1/transactions_controller.rb
class Api::V1::TransactionsController < ApiController

  def create
    from_wallet = Wallet.find(params[:wallet][:id]).address
    if params.dig("address") != "" && params.dig("address") != nil
      to = params.dig("address")
    else
      to = User.find_by_email(params.dig("to")).primary_wallet.address
    end

    amount = params.dig("amount")

    transaction = Transaction.new(
      from: from_wallet,
      to: to,
      amount: amount,
    )

    if transaction.save
      render json: { message: 'success' }, status: 200
    else
      render json: { message: 'error' }, status: 500
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :wallets
  before_action :require_login

  def new
  end
end

app/views/transactions/new.html.erb
<%= render partial: 'layouts/nav' %>
<%= render partial: 'layouts/side_menu' %>
<div class="col-sm-10 col-xs-12 main-content-area new-transaction">
  <br>
  <div class="row">
    <% if current_user && current_user.primary_wallet %>
    <div class="container">
      <div class="col-sm-10 col-sm-offset-4 col-md-6 10 col-md-offset-3">
          <div class="new-transaction card animated pulse">
            <div class="card-header">
                Send Coins
            </div>
            <div class="card-block">
              <form id="submit-transaction">
                <div class="form-group">
                  <div class="input-group input-group-lg">
                    <span class="input-group-addon" id="sizing-addon1"><i class="fa fa-user fa-fw" aria-hidden="true"></i></span>
                    <input class="form-control" placeholder="RECEIPIENT EMAIL" type="email" aria-describedby="sizing-addon1" name="to">
                  </div>
                  <div class="send-help">
                    <a href="#" data-toggle="modal" data-target="#send-help"><i class="fa fa-exclamation-circle fa-fw" aria-hidden="true"></i>Or:</a>
                  </div>
                  <div class="input-group input-group-lg">
                    <span class="input-group-addon" id="sizing-addon1"><i class="fa fa-key fa-fw" aria-hidden="true"></i></span>
                    <input class="form-control" id="from" placeholder="RECEIPIENT CLC ADDRESS" aria-describedby="sizing-addon1" name="address">
                  </div>
                  <br>
                  <hr>
                  <div class="input-group input-group-lg">
                    <span class="input-group-addon" id="sizing-addon1">CLC</i></span>
                    <input autocomplete="off" id="amount" class="form-control" type="amount" placeholder="AMOUNT" name="amount"/>
                  </div>
                  <hr>
                    <p class="wallet-select">Send From: <%= collection_select(:wallet, :id, current_user.wallets, :id, :balance_with_id ) %></p>
                  <hr>
                  <footer id="submitTransaction">
                    <input type="submit" id="sendCoin" class="btn btn-success btn-lg btn-block log" value="Send"></input>
                  </footer>
                </div>
              </form>
            </div>
          </div>
        </div>
    <% else %>
    <div class="row">
      <%= link_to "You need a wallet to get started", new_wallet_path, class: "btn btn-alert" %>
    </div>
    <% end %>
  </div>
</div>


<!-- modal -->

<div class="modal fade" id="send-help" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h1 class="modal-title" id="myModalLabel"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></h1>
      </div>
      <div class="modal-body">
        You can either send money to an email address, where it will be deposited into the recepients primary wallet, or
        send directly to a wallet address.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">Done</button>
      </div>
    </div>
  </div>
</div>