config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  get '/dashboard', to: 'dashboard#show'

  resources :wallets, only: [:new, :create]

  resource :dashboard do
    collection do
      get '/wallets/:slug', to: 'wallets#show', as: "whallet"
    end
  end

  get '/transactions/new', to: 'transactions#new'

  get "/friends", to: "address_books#show", as: :friends

  namespace :api, default: { format: :json } do
    namespace :v1 do
      resource :transactions, only: [:create]
      resource :wallets, only: [:create]
      resource :address_books, only: [:update]
      resource :phones, only: [:update]
    end
  end

end

app/views/layouts/_dash_header.html.erb
<strong><h4 class="animated fadeInUp">Welcome <%= current_user.email %></h4></strong>


  <!--  modal / -->
  <div class="modal fade" id="dash-create-wallet" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="dashboardWallet">Create a New Wallet</h4>
        </div>
        <div class="modal-body">

          <form id="wallet-form">
            <div class="form-group">
              <label for="walletName">Name </label>
              <input name="wallet_name" id="walletName" autocomplete="off" type="text" class="form-control" placeholder="15 Characters Maximum" required="true" maxlength="15">
            </div>
            <div class="form-group">
              <label for="privateKey">Private Key </label>
              <input name="private_key" id="privateKey" autocomplete="off" type="text" class="form-control" placeholder="Optional">
            </div>
            <footer id="modalSubmitButton">
              <button id="createWalletButton" type="submit" class="btn btn-success">Create</button>
            </footer>
          </form>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_flash.html.erb
<div class=" container row flash">
  <div class="col-sm-8 col-sm-offset-4">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= value %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light bg-faded">
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
  <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
    <a class="navbar-brand container" href="<%= root_path  %>">ClarkeBase</a>
    <ul class="nav navbar-nav">
      <% if !current_user %>
        <li class="nav-item container pull-xs-right">
          <a class="btn btn-success" href="<%= new_user_registration_path%>">Sign Up</a>
        </li>
        <li class="nav-item container pull-xs-right">
          <a class="btn btn-secondary-outline" href="<%= new_user_session_path  %>">Sign In</a>
        </li>
      <% end  %>
      <% if current_user %>
        <li class="nav-item container pull-xs-right">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-secondary-outline" %>
        </li>
        <li class="nav-item container pull-xs-right">
          <%= link_to "Welcome #{current_user.email}", dashboard_path, class: "btn btn-secondary-outline" %>
        </li>
      <% end  %>
    </ul>
  </div>
</nav>

app/views/layouts/_side_menu.html.erb
<div class="col-sm-2 sidebar hidden-xs">
  <ul class="nav nav-pills nav-stacked left-side">
    <br>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#collapseWallet" aria-expanded="false" aria-controls="collapseWallet"><i class="fa fa-folder-open fa-fw" aria-hidden="true"></i> Wallets</a>
      <div class="collapse wallets" id="collapseWallet">
        <% @wallets.each do |wallet| %>
          <span class="card card-block sidebar-wallet">
            <%= link_to truncate(wallet.name, length: 15, separator: ' '), whallet_dashboard_path(wallet.slug) %>
            <span class="pull-right"><%= wallet.balance %> CLC</span>
          </span>
        <% end %>
      </div>
    </li>
    <hr>
    <br>
    <li class="nav-item">
      <span class="option-image"><a class="nav-link <%= 'active' if params[:controller] == 'dashboard' %>" href="<%= dashboard_path %>"><i class="fa fa-server" aria-hidden="true"></i> Dashboard</a></span>
    </li>
    <hr>
    <br>
    <li class="nav-item">
      <span class="option-image"><a class="nav-link <%= 'active' if params[:controller] == 'transactions' %>" href="<%= transactions_new_path %>"><i class="fa fa-paper-plane fa-fw" aria-hidden="true"></i> Send ClarkeCoins</a></span>
    </li>
    <hr>
    <br>
    <li class="nav-item">
      <span class="option-image"><a class="nav-link <%= 'active' if params[:controller] == 'address_books' %>" href="<%= friends_path %>"><i class="fa fa-user-secret fa-fw" aria-hidden="true"></i>  Friends</a></span>
    </li>
    <hr>
    <br>
  </ul>
</div>
<div class="col-sm-10 col-xs-12 main-content-area">

app/views/layouts/_transactions.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <div class="card-header">
        Sent Transactions
      </div>
      <div class="scrollable">
        <table>
          <thead>
            <tr>
              <th width="200">To</th>
              <th width="200">Amount</th>
              <th width="200">Status</th>
              <th width="500">Made At</th>
            </tr>
          </thead>
          <% @sent_transactions.each do |transaction| %>
            <tbody class="sent-transactions">
              <tr>
                <td><%= truncate transaction.email("to"), length: 20 %></td>
                <td>CLC:<%= transaction.amount %></td>
                <td><%= transaction.status %></td>
                <td><%= transaction.time %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card-header">
        Received Transactions
      </div>
      <div class="scrollable">
        <table>
          <thead>
            <tr>
              <th width="400">From</th>
              <th width="400">Amount</th>
              <th width="400">Status</th>
              <th width="500">Made At</th>
            </tr>
          </thead>
          <% @received_transactions.each do |transaction| %>
          <tbody class="received-transactions">
            <tr>
              <td><%= truncate transaction.email("from"), length: 20 %></td>
              <td>CLC:<%= transaction.amount %></td>
              <td><%= transaction.status %></td>
              <td><%= transaction.time %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clarkebase</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Libre+Franklin' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway" media="screen" title="no title" charset="utf-8">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/4.0.3/sweetalert2.min.css">
  <script src="https://cdn.jsdelivr.net/sweetalert2/4.0.3/sweetalert2.min.js"></script>
  <script src="https://use.fontawesome.com/3bc48beda0.js"></script>
</head>
<body>
<%= yield %>
</body>
</html>